version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc repo-main bison build-essential curl flex g++-multilib gcc gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync
           git config --global user.name "Takeshiro"
           git config --global user.email "gianashtonreyes@gmail.com"
           git config --global color.ui false
           git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
           mkdir ~/bin
           PATH=~/bin:$PATH
           curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
           chmod a+x ~/bin/repo
           gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
           curl https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ~/bin/repo
           mkdir nbm69
           cd nbm69
           wget https://raw.githubusercontent.com/Takeshiro04/pbrp_device_xiaomi_tissot/android-9.0/.circleci/build.sh
           source build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
